### ISSUE TITLE
Failed to load the TLS Client asset: Unable to find asset tls-client-linux-amd64-1.7.5.so for version 1.7.5.

### ISSUE THREAD

**Issue by youngpay** [rawandahmad698/noble-tls#11]
Hello, reducing the initial installation size is a good way to speed up the installation by only downloading the required dependencies. However, I encountered this problem when installing under CentOS. Can you fixed? Thank you!
```
>> Dependencies folder is empty. Downloading the latest TLS release...
>> Failed to load the TLS Client asset: Unable to find asset tls-client-linux-amd64-1.7.5.so for version 1.7.5.
```
My system:
```
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1160.105.1.el7.x86_64
      Architecture: x86-64
```

**Comment by nmaisonneuve** [comment]
same for ubuntu 
>httpx->noble-tls==0.0.106->-r requirements.txt (line 8)) (4.10.0)
Installing collected packages: noble-tls
  Attempting uninstall: noble-tls
    Found existing installation: noble_tls 0.0.102
    Uninstalling noble_tls-0.0.102:
      Successfully uninstalled noble_tls-0.0.102
Successfully installed noble-tls-0.0.106
>> Failed to load the TLS Client asset: Unable to find asset tls-client-linux-ubuntu-amd64-1.7.2.so for version 1.7.2.
Traceback (most recent call last):

**Comment by rawandahmad698** [comment]
There was an issue with the naming pattern in the original tls repo, can you try now and let me know?
